### ISSUE TITLE
いいね機能

### ISSUE THREAD

**Issue by Takumi-Tajima** [Takumi-Tajima/Miniblog-Ver.2#11]
### likesテーブル、like modelを作成する

---
見積もり：15m
ゴール：コンソールからlikeインスタンスを作成して、Like.allでuser_idとpost_idを確認できるようにする

- likeマイグレーションを作成する
    - user_id
    - post_id
    - userとpostの複合インデックスが必要→同じ組み合わせは存在しない
        - [x]  rails g model like user:references post:references
        - [x]  マイグレにnull: falseとforeign_key: true
        - [x]  複合indexを貼る
            
            ```ruby
            t.index %i[user_id post_id], unique: true
            ```
            
- like modelにリレーションを追加する
    - [x]  belong_to userとpostをつける
- userとpost modelにリレーションを追加
    - [x]  has_many likes, dependent: :destroy x 2
- consoleでLikeモデルを新しく作成してみる

タスクばらし 20m

**Comment by Takumi-Tajima** [comment]
実装時間12m

**Comment by Takumi-Tajima** [comment]
### MVCの設定

---

タスクばらし 33m

ゴール

- 投稿一覧画面から、いいねをする、いいねを消せる状態にする

- ルーティング設定 1m
    - [x]  posts配下に、resource :likesでcreateとdestoryアクションだけをを記述する
    - [x]  確認
- コントローラ作成 5m
    - [x]  rails g controller users/likes_controller create destroy
        
        ```ruby
        create
        @like_post = Like.new(user_id: current_user, post_id: params[:post_id])
        @like_post.save
        redirect_to request.referer || root_path
        
        destory!
        @like_post = current_user.likes.find_by(post_id: params[:post_id])
        @like_post.destroy!
        redirect_to request.referer || root_path
        ```
        ここまで実装6m
- ビューを作成 20m
    - [ ]  view/layout/_posts.html.haml内に記述する
        
        ここはレイアウトを見て判断する

**Comment by uekkie** [comment]
```diff
- Like.new(user_id: current_user, post_id: params[:post_id])
+ current_user.likes.create!(post_id: params[:post_id])
```

関連をつかって作りたい

**Comment by uekkie** [comment]
戻り値を扱わないのであれば、`save!` `create!` をつかう

**Comment by Takumi-Tajima** [comment]
- [x] コントローラを修正
```ruby
create
@like_post = current_user.likes.create!(post_id: params[:post_id])
redirect_to request.referer || root_path

destory!
@like_post = current_user.likes.find_by(post_id: params[:post_id])
@like_post.destroy!
redirect_to request.referer || root_path
```

メモ

- 関連で作成する、が抜けていた

**Comment by Takumi-Tajima** [comment]
posts_controllerがuser配下になっていた

**Comment by Takumi-Tajima** [comment]
ここまでの時間

- タスクばらし合計：60m
  - likesテーブル、like modelを作成する：20m
  - MVC作成：33m→ミスあり
- 実装時間の合計：101m
  - likesテーブル、like modelを作成する：15m
  - MVC作成：m85
    - エラー対応：約60m

**Comment by Takumi-Tajima** [comment]
- [x]  _likes_btn.html.hamlを作成する
    - いいね判定メソッドを作成する
        - どうやって判定をするのか？
            - 中間テーブル（likesテーブル）にその投稿のIDがあれば、いいねしている（true）
            - 中間テーブル（likesテーブル）にその投稿のIDがあれば、いいねしてない（false）
                - [ ]  user.rbに下記を記述する
                    
                    ```ruby
                    def already_liked?(post)
                      self.likes.exists?(post_id: post.id)
                    end
                    ```
                    
    - _likes_btn.html.hamlに下記を記述する
        
        ```ruby
        - if user_signed_in?
          -if current_user.already_liked(post)
            = button_to post_likes_path(post_id: post), class: 'text-decoration-none', method: :delete do
        	   .i class: 'fa-regular fa-heart'
          - else
        	  = button_to post_likes_path(post_id: post), class: 'text-decoration-none', method: :post do
        	   .i class: 'fa-solid fa-heart'
        ```
        
    - _postにrenderをする
 
タスクばらし 22m

**Comment by Takumi-Tajima** [comment]
font-awsomeを入れてなかった→抜けてた

**Comment by Takumi-Tajima** [comment]
- [x]  fontawesomeを使用する
    - [x]  gem "font-awesome-rails”をインストール
    - [x]  application.cssに下記を記述してあるか確認する、なければ記入
        
        ```ruby
        /*
         *= require font-awesome
         */
        ```

**Comment by Takumi-Tajima** [comment]
上記ではできなかった。
実装時間 約60m

**Comment by Takumi-Tajima** [comment]
PR修正 +60

**Comment by Takumi-Tajima** [comment]
n + 1問題でエラーに詰まる +60m

**Comment by Takumi-Tajima** [comment]
残りのタスク
- [ ]  ゴール：いいねしたユーザー一覧を表示して、そこから各ユーザーのプロフィールページに遷移できる
    - [ ]  ユーザーのプロフィール機能を作成する
    - [ ]  いいねカウントから、ユーザーの一覧ページを表示する

**Comment by Takumi-Tajima** [comment]
ユーザーのプロフィールページ機能を作成する
- [x] 自分のプロフィールページを表示する
- [ ] 他人のプロフィールページを表示する

**Comment by Takumi-Tajima** [comment]
タスクばらし：自分のプロフィールページを表示する

---

- [x]  ルーティングを決める 3m
    - /profileでいい
    - ディレクトリ構造はusers/profile
        - [x]  resource :profile, only: %i[show edit update]
- [x]  コントローラを作成する10m
    - edit、update、showのみを許可する
        - [x]  rails g controller users/profiles show edit update
        - [x]  before action
            
            ```ruby
            private
            
            def set_user
              @post = current_user
            end
            ```
            
        - [x]  update
            
            ```ruby
            def update
              if @post.update(post_params)
                redirect_to post_path(@post), notice: t('controllers.common.updated', model: '投稿'), status: :see_other
              else
                render :edit, status: :unprocessable_entity
              end
            end
            ```
            

※上記だとdeviseで弾かれるのではなかろうか？一旦ここまで実装するか

タスクばらし→27m

**Comment by Takumi-Tajima** [comment]
controllerとviewはセットでバラすべきなのに、また忘れた

**Comment by Takumi-Tajima** [comment]
<img width="963" alt="image" src="https://github.com/Takumi-Tajima/Miniblog-Ver.2/assets/116613691/b91d27d0-5721-4560-83c0-5d7f2b821c8b">

上記のエラーが発生

**Comment by Takumi-Tajima** [comment]
ここまで実行時間:7m

**Comment by Takumi-Tajima** [comment]
set_userがpost変数で定義されていた 1m

**Comment by Takumi-Tajima** [comment]
```ruby
def user_params
  params.require(:user).permit(:about_me, :blog_url)
end
```

抜け漏れ

**Comment by Takumi-Tajima** [comment]
コントローラ分ければ、deviseのストパラは回避できるんだ

**Comment by Takumi-Tajima** [comment]
プラスの実装時間：5m
